"""
Django settings for fintrak project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!gpcd-r7$%s6f@jel34v*-xmfr%2ss*97u_u1s=spjz8myope!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    ".ngrok-free.dev",
    ".ngrok-free.app",
]

CSRF_TRUSTED_ORIGINS = [
    "https://*.ngrok-free.dev",
    "https://*.ngrok-free.app",
]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fintrak.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fintrak.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / "fintrak/static/"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# static files (CSS, JS, images)
STATIC_URL = '/static/'

# (optional) your project-level static folder for development
STATICFILES_DIRS = [BASE_DIR / 'static']

# REQUIRED for collectstatic during deploy
STATIC_ROOT = BASE_DIR / 'staticfiles'



import os

# ... other settings ...

# Use environment variable to allow Koyeb domain
# KOYEB_PUBLIC_DOMAIN is automatically set by Koyeb
ALLOWED_HOSTS = [os.environ.get('KOYEB_PUBLIC_DOMAIN', '127.0.0.1')]

# ... other settings ...

# Set DEBUG to False in a production environment
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# fintrak/settings.py

# fintrak/settings.py

MIDDLEWARE = [
    # 1. Whitenoise (for static files)
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    
    # 2. Security (handles X-Frame-Options, etc.)
    'django.middleware.security.SecurityMiddleware',
    
    # 3. Session (handles user sessions, required for login)
    'django.contrib.sessions.middleware.SessionMiddleware', 
    
    # 4. Common (handles APPEND_SLASH)
    'django.middleware.common.CommonMiddleware',
    
    # 5. CSRF (HANDLES YOUR CURRENT ERROR)
    'django.middleware.csrf.CsrfViewMiddleware', 
    
    # 6. Authentication (handles request.user)
    'django.contrib.auth.middleware.AuthenticationMiddleware', 
    
    # 7. Messages (handles message framework)
    'django.contrib.messages.middleware.MessageMiddleware', 
    
    # 8. Clickjacking
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Add this section for static files
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
